### ISSUE TITLE
ZWaveJS fails to load when running with external auth due to service worker

### ISSUE THREAD

**Issue by ajacques** [zwave-js/zwave-js-ui#3427]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.3.2

### ZwaveJS version

12.3.0

### Describe the bug

I'm using an external auth provider (nginx + [vouch proxy](https://github.com/vouch/vouch-proxy)) to protect all of my services with one SSO solution. I choose to do this instead of having separate username and passwords for different services. Effectively how it works is it checks for a cookie on all requests to ZWaveJS and redirects the browser to the login page. 

The problem is that ZWaveJS now appears to use a service worker and works as a PWA (I suspect this came in with this commit d409051b9e96939fa0510399e45693b331a34cf1) which intercepts the call to `/` and causes this to fail. When the authorization expires, I have to hard refresh the page to load it. 

What happens is the `/` page loads from the Service worker, then the `GET /api/auth-enabled` call gets a 302 Found to redirect to the login page, the app doesn't know what to do and fails to load the app. The `/` request does not hit the backend app (I've checked my logs), so it can't know that `/` is failing. The only way to bypass this is to hard refresh the page, but that's not easy on mobile phones.

### To Reproduce

1. Install ZWaveJS behind some kind of reverse proxy such as nginx
2. On the reverse proxy, enable an auth proxy that intercepts requests, such as [vouch proxy](https://github.com/vouch/vouch-proxy)
3. Try to load the ZWaveJS and see that it gives a "Network Error. Retry" and the page fails
4. Hard refresh the page (ctrl-shift-r) and notice the app loads because it bypasses the service worker for `GET /` and the app will work until the auth token expires.

### Expected behavior

I expect the ZWaveJS application to be able to handle when there's a separate auth provider and redirect to the login page. ZWaveJS does not have to specifically have to support these providers, just handle the redirects.

I see two options here:

1. When the service worker receives the `GET /` request, it revalidates with the service to see if the response includes a redirect or not. This can also be used to refresh the cache in the service worker. (basically cache-bust the `/` call because the app can't work without internet anyway)
2. When the app sees a 302 redirect for `GET /api/auth-enabled`, it follows the redirect in a full frame redirect (i.e. browser tab navigates to the new page.) This appears to be the first request that actually gets forwarded to the server so would have to be the first point the app knows there's external auth.

It seems like the service worker comes from Vite, which possibly internalizes the cache handling logic. I'm unfamiliar with what knobs it has to know whether 1 would work, but 2 should be doable in the app side. I tried changing the `Cache-Control` on `GET /`  to be `must-revalidate`, but the service worker does not respect it

**Comment by robertsLando** [comment]
> It seems like the service worker comes from Vite, which possibly internalizes the cache handling logic.

Yeah it does, maybe there is an option in vite-pwa [docs](https://vite-pwa-org.netlify.app/guide/) for that? Could you try to play with that? It's hard for me to test this as I don't have your setup

**Comment by ajacques** [comment]
I'll keep investigating to see what I can figure out. I wanted to cut this issue just in case you were more familiar with how the PWA/service-worker itself worked and had some ideas. So far I've tried changing the `Cache-Control` header on `/`, but no success yet. I'll have to dig in the code. Somebody else was asking about this style of auth in [this issue](https://github.com/zwave-js/zwave-js-ui/issues/3031#issuecomment-1747835052).

**Comment by robertsLando** [comment]
> I wanted to cut this issue just in case you were more familiar with how the PWA/service-worker itself worked and had some ideas

Unfortunately I'm not, I mean I never had the need to dig on such things, I only know that service workers act as proxy to cache requests and make your page load faster and allows to handle background tasks like push notifications and so on (at least this is what I used them for since now).

Some useful readings can be fouind here:
- https://vite-pwa-org.netlify.app/guide/service-worker-precache.html

IMO what should be done here is to switch to [`injectManifest`](https://vite-pwa-org.netlify.app/guide/inject-manifest.html ) in order to be able to provide a custom service worker code where we you can intercept requests like here: https://medium.com/@alekswebnet/setup-token-based-authentication-for-media-files-with-service-workers-and-workbox-e8674fa621f

**Comment by krissfr** [comment]
I have the same issue with another reverse proxy (CaddyV2).
unfortunatly i can't help, because i don't have the skill of knowledge required.

**Comment by robertsLando** [comment]
> This prevents the service worker from registering, though it would break push notifications if those are being used.

Them are not used, Service worker is just used to cache requests and resources

**Comment by krissfr** [comment]
After delete all cookies related to the external url, all is working fine for me with ZwaveJS UI 9.5.1

**Comment by ajacques** [comment]
Deleting the cookies will temporarily fix the issue until the session expires and you're back in the same place. The lifetime will differ depending on your auth provider.

**Comment by robertsLando** [comment]
I have just created a possible fix for this. Anyone here is able to give a try to #3519 ?

**Comment by robertsLando** [comment]
@Daniel-dev22 Please click on the top right info icon and paste the version here so I'm sure you are using the correct one

**Comment by robertsLando** [comment]
@Daniel-dev22 Ok that's correct, just wait a moment and test the new one

**Comment by robertsLando** [comment]
I also suggest to try doing an hard refresh of the page just to be sure the service worker has been updated (Ctrl+F5 on Chrome)

**Comment by robertsLando** [comment]
@Daniel-dev22 ok see if the issue appears again in next days or if it's solved now

**Comment by ajacques** [comment]
Thanks for trying to fix this. I did a bit of digging into the docs, but still haven't figured out the right direction. I deployed the `:test` branch, but it did not fix the problem for me.

The problem is that the `GET /` request does hit the service worker, which returns the cached HTML page. The JS/CSS all load from SW cache too. Then the JS calls `GET /api/auth-enabled`, which returns the following response. It doesn't matter if the SW itself processes the `GET /api/auth-enabled` or not.

```
HTTP/2 302 
date: Mon, 15 Jan 2024 18:10:44 GMT
content-type: text/html
content-length: 138
location: https://login.internal.example.com/login?url=https://zwave.internal.example.com/api/auth-enabled&vouch-failcount=&X-Vouch-Token=&error=&rd=https://zwave.internal.example.com%2Fapi%2Fauth-enabled
X-Firefox-Spdy: h2
```

This causes the JS to automatically try to follow the redirect which triggers an OPTIONS request and it fails CORS. I tried enabling CORS on this origin (`login.internal.example.com`). The JS was able to follow the direct, but then my provider redirected to my SSO provider, `github.com`, and failed CORS there.

I tried experimenting with the following to see if it was even possible to follow the redirects to get the cookies set ignoring the HTML framing problem, but this caused the request to my provider to be sent without cookies.

```js
fetch('/auth-enabled', { mode: 'no-cors', credentials: 'include', redirect: 'follow' })
```

I work on an auth provider integration at my day job, and the two options we used were redirecting the entire page or opening up a pop-up window with the auth provider and closing it later.

This leads me to believe one of two things needs to happen:
1. The `GET /` request must get proxied through to the upstream. This would reduce some of the benefits of the service worker caching, but it would be the easiest
2. The client code [here](https://github.com/zwave-js/zwave-js-ui/blob/master/src/App.vue#L1041) should catch the exception, see there's a redirect, trigger a full page navigation. Unfortunately Axios doesn't really give a great error messag to differentiate , just `Network Error`.
3. Disabling the service worker. This is my current temporary strategy. I created an ingress that returned a 404 for the `GET /registerSW.js` request.

> > I also suggest to try doing an hard refresh of the page just to be sure the service worker has been updated (Ctrl+F5 on Chrome)
> 
> Once I cleared cookies it's working both in the browser and with the "install app" pwa on Android.

@Daniel-dev22 which external auth provider are you using and how is it hooked into your reverse proxy?

**Comment by ajacques** [comment]
> > I also suggest to try doing an hard refresh of the page just to be sure the service worker has been updated (Ctrl+F5 on Chrome)
> 
> Once I cleared cookies it's working both in the browser and with the "install app" pwa on Android.

I was asking because it sounds like you'd have the same problem as me, but this response implies that the above PR appears to fix your problem. That redirect should involve an OPTIONS request which requires CORS. Now maybe Authelia handled CORS correctly, but if you had to type in a password because your Authelia session expired then that redirect would presumably fail.

**Comment by ajacques** [comment]
So this will only work if:
* Your Auth provider(s) enables CORS
* Your browser allows third party cookies (without origin isolation) in your browser, but Chrome is deprecating them (supposedly)
* and you don't need to re-authenticate to your IDP

The reason it doesn't work after you logout of Authelia is because you need to show some HTML to type in your password. Thus the only way this will work is if `window.location` changes to your IdP.

**Comment by ajacques** [comment]
> Should I [enable CORS on] zwave.domain.net?

No, there are no cross origin requests to `zwave.domain.net`. The cross origin request is to `authelia.domain.net` which is why it looks like it's partially working right now.

The only way to fully fix this issue is to do one of these:

> * The `GET /` request must get proxied through to the upstream. This would reduce some of the benefits of the service worker caching, but it would be the easiest
> 
> * The client code [here](https://github.com/zwave-js/zwave-js-ui/blob/master/src/App.vue#L1041) should catch the exception, see there's a redirect, trigger a full page navigation. Unfortunately Axios doesn't really give a great error message to differentiate , just `Network Error`. This is additionally tricky because the redirect URL will be for `/api/auth-enabled` which will break.
> 
> * Disabling the service worker. This is my current temporary strategy. I created an ingress that returned a 404 for the `GET /registerSW.js` request.

**Comment by robertsLando** [comment]
> 1. The GET / request must get proxied through to the upstream. This would reduce some of the benefits of the service worker caching, but it would be the easiest
> 2. The client code [here](https://github.com/zwave-js/zwave-js-ui/blob/master/src/App.vue?rgh-link-date=2024-01-15T19%3A17%3A59Z#L1041) should catch the exception, see there's a redirect, trigger a full page navigation. Unfortunately Axios doesn't really give a great error messag to differentiate , just Network Error.

I could try doing the point 2 and simply trigger a reload in case of an error on that call? At least I could try this approach in that PR to see if that fixes the problem. I'm not sure why the point 1 is needed

About why I enabled PWA, the reason is to make it load faster on mobile phones (thanks to the cache), also it's not hard to maintain as everything is managed internally by the VitePWA plugin. In future that would also allow me to send push notifications if we ever find a reason to add this feature

**Comment by robertsLando** [comment]
I have just implemented point 2. and now the app should reload the page when it detects a redirect in response code. Please give the `test` tag a new try and let me know

**Comment by robertsLando** [comment]
Ok let me add the 401 code so

**Comment by robertsLando** [comment]
New build triggered: https://github.com/zwave-js/zwave-js-ui/actions/runs/7572008099

**Comment by robertsLando** [comment]
I'm out of ideas so... :( dunno if the response has some headers I could use to redirect to a new page. Btw I cannot clear cookies programmatically AFAIK

**Comment by ajacques** [comment]
Ok I think I know what's going on. When you do `location.reload()` it reloads the page, but the `GET /` still hits the service worker cache, thus the reload is pointless. Additionally, I don't see the reload loop because I get a CORS failure which doesn't surface as a 302 or a 401. Axios has a default redirect count limit of 5, but instead we don't want to follow any redirects and should set the limit to 0 to identify the first redirection. Weirdly, Axios [claims](https://github.com/axios/axios/issues/674#issuecomment-279225530) it's not possible to ignore redirects due to browser limitations, however the fetch API does provide a [redirect property](https://developer.mozilla.org/en-US/docs/Web/API/Request/redirect)

But we still need to bust the cache for `/`. One idea would be to look at the `Location` header, then set `window.location = response.headers['Location']`. That'll trigger the auth login, but when we end up back at ZWave JS, we'll be looking at `/api/auth-enabled`. Presumably that'll fail to load. That endpoint could look for `Accept: text/html` and redirect, but that's very messy.

Another option, is to catch that 302 redirect, then do `location.search = `?auth=${Math.random()}`. That busts the SW cache and gets us back into ZWaveJS UI successfully. This has worked in my current testing and it should handle all types of auth providers including delegating ones such as mine. I don't have a working change because I need to figure out how to handle this Axios issue, but this seems to be the least invasive approach I've found.

**Comment by robertsLando** [comment]
> Another option, is to catch that 302 redirect, then do location.search = '?auth=${Math.random()}'. That busts the SW cache and gets us back into ZWaveJS UI successfully

Let me try this

**Comment by robertsLando** [comment]
Wait for this and let me know: https://github.com/zwave-js/zwave-js-ui/actions/runs/7581339064

**Comment by robertsLando** [comment]
@Daniel-dev22 Thanks for your feedback!

@ajacques what about you?

**Comment by ajacques** [comment]
Almost. I get a CORS failure instead of a 302 which doesn't trigger the error handler, so it doesn't have a chance to trigger the reload. Any auth provider that delegates to another identity provider like Google or GitHub will hit this issue. I can enable CORS on my provider, but can't enable it on Google or GitHub. The browser doesn't seem to give a good error message when it encounters this case. It doesn't give a 301/401 as the code is currently checking for. I'd really like to identify the 301/302 on the first redirect to know for sure it's a redirect, which would mean we need to do `maxRedirects: 0`, then check to see if the response code is 302 on the first redirect as opposed to following redirects, but this doesn't work in Axios because it uses the XHR API which can't block redirects.

This is what I came up with: https://github.com/ajacques/zwave-js-ui/commit/9f5edb1ca2c29f37ced56ed4a8d48ea8d7728c37 I don't like having this inconsistent usage of fetch and axios though.

**Comment by robertsLando** [comment]
@ajacques I see there is a work in progress but no clue when/if it will ever be merged: https://github.com/axios/axios/pull/5146

Anyway I checked your solution and yeah I agree it's not the best to use a mix of axios and fetch but I think it's worth to accept that as it fixes your issue, maybe I could also completely drop axios

**Comment by krissfr** [comment]
it's ok for me with my reverse proxy (Caddy V2)

**Comment by robertsLando** [comment]
Try with this once it ends: https://github.com/zwave-js/zwave-js-ui/actions/runs/7610315144 to see if it works even for you @krissfr and @ajacques

**Comment by raman325** [comment]
@robertsLando I am using Caddy as a reverse proxy with Authentik for forward auth. I tried the image tagged `test` and I am still getting a CORS error:
`/#/:1 Access to XMLHttpRequest at 'https://auth.example.com/application/o/authorize/?client_id=<CLIENT_ID>&redirect_uri=https%3A%2F%2Fzjsui.example.com%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=profile+email+openid+ak_proxy&state=<STATE>' (redirected from 'https://zjsui.example.com/api/auth-enabled') from origin 'https://zjsui.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by ajacques** [comment]
@robertsLando `zwave-js-ui: 9.7.1.31e37ce` works for me

@raman325 Are you running `9.7.1.31e37ce`? What browser is this? Did you hard-refresh to load the latest version of the code before testing? Can you screenshot the network tab or share the request/responses (minus any sensitive info)? The latest commit should not be following any redirects, so there shouldn't be a CORS error.

**Comment by raman325** [comment]
must not have done a hard refresh, it appears to be working now. Versions as follows:
zwave-js-ui: 9.7.1.31e37ce
zwave-js: 12.4.1
Google Chrome Version 120.0.6099.234 (Official Build) (arm64)

**Comment by robertsLando** [comment]
Ok seems we are done now so 🎉 Thanks so much @ajacques for the tips and @raman325 @krissfr for the feedbacks!

**Comment by ajacques** [comment]
Awesome! Thanks for fixing this issue!

**Comment by robertsLando** [comment]
@Daniel-dev22 nothing changed on code to cause that AFAIK

**Comment by robertsLando** [comment]
@Daniel-dev22 could you try to test the commit before that to see if that is working? If so we should find a way to make both work...

**Comment by robertsLando** [comment]
> Hm I tried 9.8.0 and cleared cookies + cache and tried a different browser I never used with zwave js UI to avoid any cache issues and I get the same error which is odd.

That is odd yeah because I just checked and 9.8.0 version is the right before that commit so I don't think that's the root cause.


@ajacques Is it still working for you?

**Comment by robertsLando** [comment]
@Daniel-dev22 CORS are enabled on my end because otherwise it wouldn't work even for me when developing, you should check if your proxy actually is blocking cors for some reason?

**Comment by robertsLando** [comment]
Shouldn't you allow also zwave.domain.net?

**Comment by ajacques** [comment]
I just upgraded to 9.9.1 and the login redirect does not appear to be working correctly. It looks like it tried to follow the redirect which means the max redirect limit wasn't hit. I will have to investigate further in the next few days. CORS is not the fix for this. The JS needs to see the redirect and use that to trigger a full frame redirect. Enabling CORS means that the browser followed the redirect and is going to get an unparseable response payload.

**Comment by ajacques** [comment]
Plot twist. It is working for me on 9.9.1 correctly. I think the JS was cached from an older version in the service worker cache on the computer I tested on. @Daniel-dev22, if you're saying it's not working, you should be able to hard refresh and get it to login, then does the version in the top right show 9.9.1 or something modern?

**Comment by robertsLando** [comment]
It could be the service worker failed to refresh the cache for some reason related to the proxy maybe...

**Comment by ajacques** [comment]
I suppose it is possible that the SW tried to fetch the latest version, then failed because the auth proxy rejected it, but in the above case Daniel-dev22 suggested that it used to work for them, then stopped. In theory, they should have had a version cached. I could see how that could cause my problem if I have a pre-9.8.x cached version, but not post-9.x.x cached JS in the SW cache (which had the new auth check.)

However, that gives me an idea. I'm going to remove `/manifest.webmanifest` and `/assets/*` from the Auth proxy and then try to test the next upgrade and see what happens. That should enable the service worker to be able to fetch the latest assets at any point.

**Comment by ajacques** [comment]
Unfortunately, I haven't been able to reproduce the issue since then. I do have `/sw.js` and `/assets/*` permitted to bypass the auth check and have been able to go through some upgrades without issues and I think this should be enough. But I haven't confirmed that this fixes it with a negative check (i.e. it doesn't work before making this change.) Testing is slow because I'm running out of releases to test on.

**Comment by sushain97** [comment]
👋 I just wanted to chime in and say thanks a bunch to @robertsLando and @ajacques! My setup is Caddy + Auhentik and things seem to work with no errors in network panel after I delete cookies + hard refresh. I didn't test with a stale Authentik session, though.


Here's my config for anyone who drops in:

```Caddyfile
zwave.mydomain {
	reverse_proxy /outpost.goauthentik.io/* http://authentik-server.idp.svc.cluster.local
	forward_auth http://authentik-server.idp.svc.cluster.local {
		uri /outpost.goauthentik.io/auth/caddy
		copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version
		trusted_proxies private_ranges
	}
	reverse_proxy http://zwave.home.svc.cluster.local
}
```

```terraform
resource "authentik_provider_proxy" "zwave" {
  name                  = "zwave"
  external_host         = "https://zwave.mydomain"
  mode                  = "forward_single"
  access_token_validity = "days=3"
  skip_path_regex       = "^/manifest.webmanifest$"
  authorization_flow    = data.authentik_flow.default-authorization-flow.id
  authentication_flow   = data.authentik_flow.default-authentication-flow.id
}

resource "authentik_application" "zwave" {
  name              = "zwave"
  slug              = "zwave"
  meta_icon         = "https://zwave-js.github.io/zwave-js-ui/_images/app_logo.svg"
  protocol_provider = authentik_provider_proxy.zwave.id
}

resource "authentik_policy_binding" "zwave-access" {
  for_each = { 0 : data.authentik_user.sushain }
  target   = authentik_application.zwave.uuid
  user     = each.value.pk
  order    = 0
}
```

The only interesting bit is really `skip_path_regex = "^/manifest.webmanifest$"` which I added after requests there 302'd to Authentik and then failed with CORS errors.

**Comment by robertsLando** [comment]
Could someone of you guys confirm me if #3825 could break your setup?

**Comment by robertsLando** [comment]
Unfortunately nope as it's on a fork, but I can merge it and then you can use `master` to check.

**Comment by robertsLando** [comment]
Wait for: https://github.com/zwave-js/zwave-js-ui/actions/runs/10061183639/job/27810599866

**Comment by ajacques** [comment]
LGTM from an external auth provider perspective.

**Comment by robertsLando** [comment]
Thanks for your feedback @ajacques ! :)

**Comment by robertsLando** [comment]
@Daniel-dev22  🙏🏼

**Comment by jaimevisser** [comment]
Can reproduce with Traefik and basic auth as well.
